# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release #bioc-release or bioc-devel

sudo: false
cache:
  - packages
  - apt

compiler:
  - clang

r_packages:
  - covr

before_install:
  - sudo apt-get -y install libgsl-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'sessionInfo()'

after_failure:
  - ./travis-tool.sh dump_logs
  - Rscript -e 'sessionInfo()'
